schemaVersion: 2.1.0
metadata:
  name: cplus-plus-devspaces
projects:
  - git: 
      remotes:
        origin: 'https://github.com/froberge/devspaces-cplus-plus'
    name: devspaces-cplus-plus
components:
  - name: tools
    container:
      env:
        - name: CHE_DASHBOARD_URL
          value: 'https://devspaces.apps.home.myocp.net'
        - name: CHE_PLUGIN_REGISTRY_URL
          value: 'https://devspaces.apps.home.myocp.net/plugin-registry/v3'
        - name: CHE_PLUGIN_REGISTRY_INTERNAL_URL
          value: 'http://plugin-registry.devspaces.svc:8080/v3'
        - name: OPENVSX_REGISTRY_URL
          value: 'https://open-vsx.org'
      image: registry.redhat.io/devspaces/udi-rhel8:3.5
      memoryRequest: 1Gi
      memoryLimit: 3Gi
      cpuLimit: 2000m
      cpuRequest: 500m
commands:
  - id: build-app
    exec:
      label: 1. Build App
      commandLine: g++ -o App main.cpp
      component: tools
      group:
        isDefault: true
        kind: build
      workingDir: '${PROJECTS_ROOT}/devspaces-cplus-plus/app'
  - id: run-app
    exec:
      label: 2. Run App
      commandLine: ./App
      component: tools
      group:
        isDefault: true
        kind: run
      workingDir: '${PROJECTS_ROOT}/devspaces-cplus-plus/app'

